name: build
on: [ push, pull_request ]
jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [ clang, gcc, gcc-9, gcc-10, gcc-11, gcc-12 ]
    steps:
      - name: Add repository
        run: sudo apt-add-repository -y "ppa:ubuntu-toolchain-r/test"
      - name: Install packages
        run: sudo apt install gettext gcc-9 gcc-10 gcc-11 gcc-12
      - uses: actions/checkout@v2
      - name: Autoconf
        run: autoreconf -i -f
      - name: Configure
        run: ./configure
        env:
          CC: ${{ matrix.compiler }}
      - name: Make
        run: make
      - name: Run tests
        id: make-check
        run: make check
        continue-on-error: true
      - name: Upload test log
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-suite-log
          path: test-suite.log
          retention-days: 5
      - name: Generate corpus
        run: make generate_corpus
  macos:
    runs-on: macos-latest
    strategy:
      matrix:
        compiler: [ clang, gcc ]
    steps:
      - name: Install packages
        run: brew install automake libtool
      - uses: actions/checkout@v2
      - name: Autoconf
        run: autoreconf -i -f -I $(brew --prefix)/share/gettext/m4
      - name: Configure
        run: ./configure
        env:
          CC: ${{ matrix.compiler }}
      - name: Make
        run: make
      - name: Run tests
        id: make-check
        run: make check
        continue-on-error: true
      - name: Upload test log
        if: steps.make-check.outcome == 'failure'
        uses: actions/upload-artifact@v4
        with:
          name: test-suite-log
          path: test-suite.log
          retention-days: 5
      - name: Generate corpus
        run: make generate_corpus
  windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            autotools
            base-devel
            gcc
            libiconv-devel
      - uses: actions/checkout@v2
      - name: Autoconf
        run: autoreconf -i -f
      - name: Configure
        run: ./configure
      - name: Make
        run: make
      - name: Test
        id: make-check
        run: make check
        continue-on-error: true
      - name: Upload test log
        if: steps.make-check.outcome == 'failure'
        uses: actions/upload-artifact@v4
        with:
          name: test-suite-log
          path: test-suite.log
          retention-days: 5
